name: Validate Conventional Commits

on:
  pull_request:
    branches:
      - main 

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar o pip
        run: pip install pip

      - name: Instalar as dependencias do projeto
        run: pip install GitPython==3.1.43

      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3.3.0

      - name: Validando formato do commit
        run: python check-commit.py
