name: Validate Conventional Commits

on:
  push:
    branches:
      - main 

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3.3.0

      - name: teste commit
        run: python check-commit.py
