name: pipeline
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Copia os arquivos do repositório
            run: actions/checkout@v3.3.0
        
          - name: Roda outro comando!
            run: echo $(ls)


